[36mINFO[0m[2022-04-08T11:27:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:27:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:27:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:27:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[36mINFO[0m[2022-04-08T11:27:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:00Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:00Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:28:00Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:28:00Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:28:00Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:05Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:28:05Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:36Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:36Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:36Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:35:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:35:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:35:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:05Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:05Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:05Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:pq: the database system is starting up. 
[31mERRO[0m[2022-04-08T11:36:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:pq: the database system is starting up. 
[31mERRO[0m[2022-04-08T11:36:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]main.go:14 main.main failed to start server due to error: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]main.go:14 main.main failed to start server due to error: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T11:43:49Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba5a0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:43:49Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba5a0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:15Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:15Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba660 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba660 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000ecc0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000ecc0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:31Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:31Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:31Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:34Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:34Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:34Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:38Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:38Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:38Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:10Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:10Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:10Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:00:43Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-original.jpg: no such file or directory. 
[31mERRO[0m[2022-04-08T12:00:43Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-original.jpg: no such file or directory. 
[31mERRO[0m[2022-04-08T12:01:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00009ecf0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:01:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00009ecf0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:14Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e690 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:14Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e690 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:31Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e6f0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:31Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e6f0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[36mINFO[0m[2022-04-08T12:03:54Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:54Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:03:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:03:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:03:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:04:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:04:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:10Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:04:10Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:04:28Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at end of input. 
[31mERRO[0m[2022-04-08T12:04:28Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at end of input. 
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:41Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:41Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:41Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:08:11Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[31mERRO[0m[2022-04-08T12:08:11Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:40Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:40Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:40Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:17:27Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: relation "image" does not exist. 
[31mERRO[0m[2022-04-08T12:17:27Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: relation "image" does not exist. 
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:19:18Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:19:18Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:19:18Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:19:32Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:19:32Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:20:04Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:20:04Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-12T07:40:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T07:40:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T07:40:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T07:40:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T07:40:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T07:40:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T07:40:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006c150 0xc000052020}) 
[31mERRO[0m[2022-04-12T07:40:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006c150 0xc000052020}) 
[31mERRO[0m[2022-04-12T07:40:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006c150 0xc000052020}) 
[31mERRO[0m[2022-04-12T07:40:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006c150 0xc000052020}) 
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T07:40:08Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:38:49Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:49Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:49Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:38:49Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:38:49Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:38:49Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:38:49Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000288000 0xc000290000}) 
[31mERRO[0m[2022-04-12T08:38:49Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000288000 0xc000290000}) 
[31mERRO[0m[2022-04-12T08:38:49Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000288000 0xc000290000}) 
[31mERRO[0m[2022-04-12T08:38:49Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000288000 0xc000290000}) 
[36mINFO[0m[2022-04-12T08:38:56Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:56Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:56Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:38:56Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:38:56Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:38:56Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:38:56Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:38:56Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:38:56Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:38:56Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc00004e020}) 
[36mINFO[0m[2022-04-12T08:39:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:39:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:39:04Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:39:04Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:39:04Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286120 0xc00029c000}) 
[31mERRO[0m[2022-04-12T08:39:04Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286120 0xc00029c000}) 
[31mERRO[0m[2022-04-12T08:39:04Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286120 0xc00029c000}) 
[31mERRO[0m[2022-04-12T08:39:04Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286120 0xc00029c000}) 
[36mINFO[0m[2022-04-12T08:39:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:39:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:39:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:39:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.19.0.18:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:39:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe90 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T08:39:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe90 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T08:39:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe90 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T08:39:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe90 0xc0001cf680}) 
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:39:13Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:44:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:44:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:44:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:44:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:44:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000076750 0xc00004ef60}) 
[31mERRO[0m[2022-04-12T08:44:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000076750 0xc00004ef60}) 
[31mERRO[0m[2022-04-12T08:44:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000076750 0xc00004ef60}) 
[31mERRO[0m[2022-04-12T08:44:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000076750 0xc00004ef60}) 
[36mINFO[0m[2022-04-12T08:44:51Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:51Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:44:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:44:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:44:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:44:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:44:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:44:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:44:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[36mINFO[0m[2022-04-12T08:45:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:45:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:45:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:45:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:45:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba40 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:45:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba40 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:45:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba40 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:45:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba40 0xc0001cf540}) 
[36mINFO[0m[2022-04-12T08:45:11Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:11Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:11Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:45:11Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:45:11Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:45:11Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.15:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:45:11Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:45:11Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:45:11Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:45:11Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:45:18Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T08:59:11Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:11Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:59:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:59:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:12Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:12Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[36mINFO[0m[2022-04-12T08:59:26Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:26Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:59:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:59:27Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:27Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:27Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:27Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:27Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:27Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[36mINFO[0m[2022-04-12T08:59:45Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:45Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:45Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:59:45Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:59:45Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:45Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:45Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:45Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:45Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T08:59:45Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T08:59:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.13:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T08:59:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba10 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:59:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba10 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:59:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba10 0xc0001cf540}) 
[31mERRO[0m[2022-04-12T08:59:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cba10 0xc0001cf540}) 
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:11:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:11:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:11:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:11:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:11:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:11:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:11:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:11:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020f660}) 
[36mINFO[0m[2022-04-12T09:11:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:11:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:11:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:11:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:11:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe30 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T09:11:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe30 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T09:11:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe30 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T09:11:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe30 0xc0001cf680}) 
[36mINFO[0m[2022-04-12T09:12:21Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:21Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:21Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:12:21Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:12:21Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:12:21Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:12:21Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:12:21Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:12:21Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T09:12:21Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:12:32Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-12T09:19:45Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[31mERRO[0m[2022-04-12T09:19:45Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[31mERRO[0m[2022-04-12T09:29:49Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:56855->127.0.0.11:53: i/o timeout. 
[31mERRO[0m[2022-04-12T09:29:49Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:56855->127.0.0.11:53: i/o timeout. 
[31mERRO[0m[2022-04-12T09:30:20Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:38084->127.0.0.11:53: i/o timeout. 
[31mERRO[0m[2022-04-12T09:30:20Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:38084->127.0.0.11:53: i/o timeout. 
[31mERRO[0m[2022-04-12T09:30:32Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:37655->127.0.0.11:53: i/o timeout. 
[31mERRO[0m[2022-04-12T09:30:32Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp: lookup imagedb on 127.0.0.11:53: read udp 127.0.0.1:37655->127.0.0.11:53: i/o timeout. 
[36mINFO[0m[2022-04-12T09:34:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:03Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:34:03Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:34:03Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:03Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:03Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T09:34:03Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T09:34:03Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T09:34:03Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[36mINFO[0m[2022-04-12T09:34:13Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:13Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:13Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:34:13Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:34:13Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:13Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:13Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000200ff0 0xc00020e6a0}) 
[31mERRO[0m[2022-04-12T09:34:13Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000200ff0 0xc00020e6a0}) 
[31mERRO[0m[2022-04-12T09:34:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000200ff0 0xc00020e6a0}) 
[31mERRO[0m[2022-04-12T09:34:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000200ff0 0xc00020e6a0}) 
[36mINFO[0m[2022-04-12T09:34:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:34:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T09:34:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.11:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T09:34:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066e10 0xc00004efe0}) 
[31mERRO[0m[2022-04-12T09:34:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066e10 0xc00004efe0}) 
[31mERRO[0m[2022-04-12T09:34:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066e10 0xc00004efe0}) 
[31mERRO[0m[2022-04-12T09:34:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066e10 0xc00004efe0}) 
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T09:39:19Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-12T09:39:55Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[31mERRO[0m[2022-04-12T09:39:55Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[36mINFO[0m[2022-04-12T11:43:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:43:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:43:59Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:43:59Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T11:43:59Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:43:59Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:43:59Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d40 0xc00020e8c0}) 
[31mERRO[0m[2022-04-12T11:43:59Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d40 0xc00020e8c0}) 
[31mERRO[0m[2022-04-12T11:43:59Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d40 0xc00020e8c0}) 
[31mERRO[0m[2022-04-12T11:43:59Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d40 0xc00020e8c0}) 
[36mINFO[0m[2022-04-12T11:44:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:44:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T11:44:16Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:16Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:16Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:16Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:16Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:16Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[36mINFO[0m[2022-04-12T11:44:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:44:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T11:44:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T11:44:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[36mINFO[0m[2022-04-12T11:44:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:44:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T11:44:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.8:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T11:44:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068600 0xc00020e760}) 
[31mERRO[0m[2022-04-12T11:44:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068600 0xc00020e760}) 
[31mERRO[0m[2022-04-12T11:44:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068600 0xc00020e760}) 
[31mERRO[0m[2022-04-12T11:44:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068600 0xc00020e760}) 
[36mINFO[0m[2022-04-12T11:44:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:50Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:44:50Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T11:44:51Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T11:44:51Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-12T11:48:38Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[31mERRO[0m[2022-04-12T11:48:38Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[31mERRO[0m[2022-04-12T11:48:38Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[31mERRO[0m[2022-04-12T11:48:38Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-HD720p.jpg: no such file or directory. 
[31mERRO[0m[2022-04-12T11:49:22Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[31mERRO[0m[2022-04-12T11:49:22Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[36mINFO[0m[2022-04-12T12:18:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:18:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:18:22Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:22Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:22Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:18:22Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:18:22Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a120 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:18:22Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a120 0xc00004e020}) 
[36mINFO[0m[2022-04-12T12:18:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:35Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:18:35Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:18:35Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:35Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:35Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:18:35Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:18:35Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:18:35Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020f660}) 
[36mINFO[0m[2022-04-12T12:18:48Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:48Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:48Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:18:48Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:18:48Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:48Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:18:48Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe60 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T12:18:48Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe60 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T12:18:48Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe60 0xc0001cf680}) 
[31mERRO[0m[2022-04-12T12:18:48Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001cbe60 0xc0001cf680}) 
[36mINFO[0m[2022-04-12T12:19:15Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:19:15Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:19:15Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:19:15Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:19:15Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:19:15Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.20.0.7:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:19:15Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T12:19:15Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T12:19:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[31mERRO[0m[2022-04-12T12:19:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a40 0xc00020f520}) 
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:19:27Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:35:27Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:27Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:35:27Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:35:27Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:35:27Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:35:27Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T12:35:27Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T12:35:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T12:35:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[36mINFO[0m[2022-04-12T12:35:51Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:51Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:35:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:35:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:35:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:35:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:35:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:35:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:35:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020f660}) 
[36mINFO[0m[2022-04-12T12:36:07Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:07Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:07Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:36:07Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:36:07Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:36:07Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.14:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:36:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:36:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:36:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[31mERRO[0m[2022-04-12T12:36:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020f660}) 
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:36:18Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:50:33Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-12T12:55:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:59Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:55:59Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:55:59Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.5:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:55:59Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.5:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:55:59Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:59Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:59Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:59Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[36mINFO[0m[2022-04-12T12:56:15Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:15Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-12T12:56:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-12T12:56:16Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.5:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:56:16Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.5:5432: connect: connection refused. 
[31mERRO[0m[2022-04-12T12:56:16Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002840f0 0xc0002a2040}) 
[31mERRO[0m[2022-04-12T12:56:16Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002840f0 0xc0002a2040}) 
[31mERRO[0m[2022-04-12T12:56:16Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002840f0 0xc0002a2040}) 
[31mERRO[0m[2022-04-12T12:56:16Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002840f0 0xc0002a2040}) 
