[36mINFO[0m[2022-04-08T11:27:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:50Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:27:51Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:27:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:51Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[31mERRO[0m[2022-04-08T11:27:51Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7a40 0xc0001cab20}) 
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:27:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:27:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:27:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[31mERRO[0m[2022-04-08T11:27:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000092000 0xc00009a000}) 
[36mINFO[0m[2022-04-08T11:27:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:27:59Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:00Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:00Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:28:00Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:28:00Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.21.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:28:00Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:28:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000064150 0xc00004a020}) 
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:04Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:28:05Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:28:05Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[31mERRO[0m[2022-04-08T11:33:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201f80 0xc00020ec60}) 
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:36Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:36Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:36Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:36Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:33:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:39Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:33:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:39Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.22.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:33:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[31mERRO[0m[2022-04-08T11:33:39Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006e150 0xc00004a020}) 
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:33:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:35:57Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:35:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:35:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:35:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[31mERRO[0m[2022-04-08T11:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286000 0xc00028e000}) 
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:02Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:05Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:05Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:05Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:05Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:36:05Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:08Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:08Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.23.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:36:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-08T11:36:08Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:12Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:36:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:pq: the database system is starting up. 
[31mERRO[0m[2022-04-08T11:36:12Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:pq: the database system is starting up. 
[31mERRO[0m[2022-04-08T11:36:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]main.go:14 main.main failed to start server due to error: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[31mERRO[0m[2022-04-08T11:36:12Z]main.go:14 main.main failed to start server due to error: %!w(*pq.Error=&{FATAL 57P03 the database system is starting up            postmaster.c 2325 ProcessStartupPacket}) 
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:36:16Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T11:43:49Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba5a0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:43:49Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba5a0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:15Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:15Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba660 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc0002ba660 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000ecc0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T11:46:16Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000ecc0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T11:56:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:31Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:31Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:31Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:31Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[31mERRO[0m[2022-04-08T11:56:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000247e60 0xc00024ac60}) 
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:34Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:34Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:34Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:34Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[31mERRO[0m[2022-04-08T11:56:34Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000209e60 0xc000216c40}) 
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:38Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T11:56:38Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:38Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.26.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T11:56:38Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T11:56:38Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T11:56:42Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:02Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:02Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:00:06Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:10Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:00:10Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:10Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.27.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:00:10Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[31mERRO[0m[2022-04-08T12:00:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002019b0 0xc00004a500}) 
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:00:14Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:00:43Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-original.jpg: no such file or directory. 
[31mERRO[0m[2022-04-08T12:00:43Z]Image_repository.go:189 image/domain/store.(*ImageRepository).GetImageFromLocalStore Error occured while opening image file. Err msg: open images/pet/id-1/image-original.jpg: no such file or directory. 
[31mERRO[0m[2022-04-08T12:01:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00009ecf0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:01:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00009ecf0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:12Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e600 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:14Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e690 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:14Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e690 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:31Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e6f0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[31mERRO[0m[2022-04-08T12:02:31Z]saveJPEG.go:30 image/internal/handlers/image.SaveJPEGHandle.func1 error occured while reading multi form data request. Err msg: request Content-Type isn't multipart/form-data. Requests body: &{0xc00000e6f0 <nil> <nil> false true {0 0} false false false 0x68af40} 
[36mINFO[0m[2022-04-08T12:03:54Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:54Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:03:55Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:03:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:55Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:55Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:03:58Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:03:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:58Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:03:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:03:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e30 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:01Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:04:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:01Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:06Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:04:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:06Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.28.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:04:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:04:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e60 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:09Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:04:10Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:04:10Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:04:28Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at end of input. 
[31mERRO[0m[2022-04-08T12:04:28Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at end of input. 
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:28Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:28Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:06:28Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201e90 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[31mERRO[0m[2022-04-08T12:06:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000062690 0xc00004a4e0}) 
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:41Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:41Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:41Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:41Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[31mERRO[0m[2022-04-08T12:06:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201a10 0xc00020eb00}) 
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:43Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:06:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:43Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.29.0.3:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:06:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[31mERRO[0m[2022-04-08T12:06:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000066120 0xc00004a020}) 
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:06:46Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:08:11Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[31mERRO[0m[2022-04-08T12:08:11Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: syntax error at or near "ownerId". 
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:33Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:33Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[31mERRO[0m[2022-04-08T12:16:33Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000201d70 0xc00020ec40}) 
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:37Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:37Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:37Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e30 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:40Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:40Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:40Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:40Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[31mERRO[0m[2022-04-08T12:16:40Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7e60 0xc0001cac60}) 
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:42Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:16:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:42Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.30.0.2:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:16:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[31mERRO[0m[2022-04-08T12:16:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000286150 0xc00029e000}) 
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:16:44Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[31mERRO[0m[2022-04-08T12:17:27Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: relation "image" does not exist. 
[31mERRO[0m[2022-04-08T12:17:27Z]Image_repository.go:107 image/domain/store.(*ImageRepository).Update Error occured while updating image. Err msg: pq: relation "image" does not exist. 
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:18Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-04-08T12:19:18Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:19:18Z]store.go:62 image/domain/store.(*Store).Open Can't open DB. Err msg:dial tcp 172.31.0.4:5432: connect: connection refused. 
[31mERRO[0m[2022-04-08T12:19:18Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]server.go:39 image/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[31mERRO[0m[2022-04-08T12:19:18Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001c7920 0xc0001ca7c0}) 
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:35 image/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:37 image/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:19:22Z]server.go:58 image/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1115 ...       
[36mINFO[0m[2022-04-08T12:19:32Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:19:32Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:20:04Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
[36mINFO[0m[2022-04-08T12:20:04Z]Image_repository.go:121 image/domain/store.(*ImageRepository).Update Image with id 1 was updated                  
