[36mINFO[0m[2022-02-15T21:45:47+03:00]server.go:34 authentication/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-02-15T21:45:47+03:00]server.go:34 authentication/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-02-15T21:45:47+03:00]server.go:36 authentication/internal/server.(*Server).Start User store opening ...                       
[36mINFO[0m[2022-02-15T21:45:47+03:00]server.go:36 authentication/internal/server.(*Server).Start User store opening ...                       
[31mERRO[0m[2022-02-15T21:45:50+03:00]server.go:38 authentication/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> <nil> 0xc00029a680}) 
[31mERRO[0m[2022-02-15T21:45:50+03:00]server.go:38 authentication/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> <nil> 0xc00029a680}) 
[31mERRO[0m[2022-02-15T21:45:50+03:00]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> <nil> 0xc00029a680}) 
[31mERRO[0m[2022-02-15T21:45:50+03:00]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> <nil> 0xc00029a680}) 
[36mINFO[0m[2022-03-23T13:35:29+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:35:29+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:35:30+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[31mERRO[0m[2022-03-23T13:35:30+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[36mINFO[0m[2022-03-23T13:37:06+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdbtest port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:37:06+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdbtest port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:37:08+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp: lookup authdbtest: no such host 
[31mERRO[0m[2022-03-23T13:37:08+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp: lookup authdbtest: no such host 
[36mINFO[0m[2022-03-23T13:43:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:43:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:43:55+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[31mERRO[0m[2022-03-23T13:43:55+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[36mINFO[0m[2022-03-23T13:46:31+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:46:31+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:46:31+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[31mERRO[0m[2022-03-23T13:46:31+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "user" не существует 
[36mINFO[0m[2022-03-23T13:46:46+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=usasdaser password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:46:46+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=5432 user=usasdaser password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:46:46+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "usasdaser" не существует 
[31mERRO[0m[2022-03-23T13:46:46+03:00]store.go:48 auth/domain/store.(*Store).Open Can't ping DB. Err msg: pq: роль "usasdaser" не существует 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:32+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:47:55+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:48:08+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:48:08+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:48:08+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:48:08+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:01+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:01+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:01+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:01+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:46+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:46+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:46+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:46+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T13:53:47+03:00]user_repository.go:36 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T13:53:47+03:00]user_repository.go:36 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T13:53:47+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: <nil>                
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: <nil>                
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: <nil>                
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: <nil>                
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:19 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:00:24+03:00]user_repository.go:19 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:00:24+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:24 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:19 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:01:25+03:00]user_repository.go:19 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:01:25+03:00]store.go:39 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:57 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:57 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:57 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:06:24+03:00]user_repository.go:57 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:06:24+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: Scan error on column index 4, name "role": sql/driver: couldn't convert "client" into type bool 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: Scan error on column index 4, name "role": sql/driver: couldn't convert "client" into type bool 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:07:05+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:07:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:05+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:06+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:06+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:08:06+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:08:06+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:08:06+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:08:06+03:00]user_repository.go:74 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:08:06+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:06+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:08:58+03:00]user_repository.go:50 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:08:58+03:00]user_repository.go:50 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:08:58+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]user_repository.go:125 auth/domain/store.(*UserRepository).Delete User with id 19 was deleted                  
[36mINFO[0m[2022-03-23T14:09:47+03:00]user_repository.go:125 auth/domain/store.(*UserRepository).Delete User with id 19 was deleted                  
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:09:47+03:00]user_repository.go:121 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:09:47+03:00]user_repository.go:121 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:09:47+03:00]user_repository.go:111 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T14:09:47+03:00]user_repository.go:111 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:09:47+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]user_repository.go:179 auth/domain/store.(*UserRepository).Update User with id 20 was updated                  
[36mINFO[0m[2022-03-23T14:10:23+03:00]user_repository.go:179 auth/domain/store.(*UserRepository).Update User with id 20 was updated                  
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:10:23+03:00]user_repository.go:175 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:10:23+03:00]user_repository.go:175 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:10:23+03:00]user_repository.go:164 auth/domain/store.(*UserRepository).Update Erorr occured while updating user. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:10:23+03:00]user_repository.go:164 auth/domain/store.(*UserRepository).Update Erorr occured while updating user. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:10:23+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:11:15+03:00]user_repository.go:204 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T14:11:15+03:00]user_repository.go:204 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T14:11:15+03:00]user_repository.go:193 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T14:11:15+03:00]user_repository.go:193 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:11:15+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:13+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:20+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:20+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:32+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:36+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:26 auth/domain/store.(*UserRepository).Create email is used. Err msg: true                 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:84 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:84 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:21 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:84 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:84 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:50 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:50 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:101 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:101 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:101 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:101 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]user_repository.go:125 auth/domain/store.(*UserRepository).Delete User with id 32 was deleted                  
[36mINFO[0m[2022-03-23T14:18:37+03:00]user_repository.go:125 auth/domain/store.(*UserRepository).Delete User with id 32 was deleted                  
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:121 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:121 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:111 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:111 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]user_repository.go:179 auth/domain/store.(*UserRepository).Update User with id 33 was updated                  
[36mINFO[0m[2022-03-23T14:18:37+03:00]user_repository.go:179 auth/domain/store.(*UserRepository).Update User with id 33 was updated                  
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:175 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:175 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:164 auth/domain/store.(*UserRepository).Update Erorr occured while updating user. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T14:18:37+03:00]user_repository.go:164 auth/domain/store.(*UserRepository).Update Erorr occured while updating user. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:37+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T14:18:38+03:00]user_repository.go:204 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T14:18:38+03:00]user_repository.go:204 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T14:18:38+03:00]user_repository.go:193 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T14:18:38+03:00]user_repository.go:193 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T14:18:38+03:00]store.go:45 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 7 was updated                   
[36mINFO[0m[2022-03-23T20:01:48+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 7 was updated                   
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T20:01:48+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:01:48+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:03+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:03:04+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:03:04+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:03:04+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T20:03:04+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:04+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 11 was updated                  
[36mINFO[0m[2022-03-23T20:03:10+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 11 was updated                  
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T20:03:10+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:03:10+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:20+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:20+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 13 was updated                  
[36mINFO[0m[2022-03-23T20:04:21+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 13 was updated                  
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T20:04:21+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:04:21+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 15 was updated                  
[36mINFO[0m[2022-03-23T20:07:31+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 15 was updated                  
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:188 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:188 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T20:07:31+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:07:31+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T20:09:07+03:00]user_repository.go:217 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T20:09:07+03:00]user_repository.go:217 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T20:09:07+03:00]user_repository.go:206 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T20:09:07+03:00]user_repository.go:206 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T20:09:07+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]testing.go:52 auth/domain/store.TestStore Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:19+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:25 auth/domain/store.(*UserRepository).Create email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:83 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:83 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:20 auth/domain/store.(*UserRepository).Create Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:83 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:83 auth/domain/store.(*UserRepository).FindByEmail Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:49 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:49 auth/domain/store.(*UserRepository).GetAll Eror occured while getting all users. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:100 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:100 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: no rows in result set 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:100 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:100 auth/domain/store.(*UserRepository).FindByID Eror occure while searching user by id. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]user_repository.go:124 auth/domain/store.(*UserRepository).Delete User with id 15 was deleted                  
[36mINFO[0m[2022-03-23T23:27:20+03:00]user_repository.go:124 auth/domain/store.(*UserRepository).Delete User with id 15 was deleted                  
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:120 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:120 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:110 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:110 auth/domain/store.(*UserRepository).Delete Error occured while deleting user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 16 was updated                  
[36mINFO[0m[2022-03-23T23:27:20+03:00]user_repository.go:192 auth/domain/store.(*UserRepository).Update User with id 16 was updated                  
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:188 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:188 auth/domain/store.(*UserRepository).Update Error occured while updating user. Err msg:No rows affected. 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:141 auth/domain/store.(*UserRepository).Update email is used. Err msg: Email already in use 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:136 auth/domain/store.(*UserRepository).Update Eror during checking users email or password. Err msg: sql: database is closed 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:217 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:217 auth/domain/store.(*UserRepository).VerifyEmail No rows was affected, possible reason: no user with such ID, err msg: No rows affected 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:206 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[31mERRO[0m[2022-03-23T23:27:20+03:00]user_repository.go:206 auth/domain/store.(*UserRepository).VerifyEmail Error occured while verifying user. Err msg:sql: database is closed. 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-23T23:27:20+03:00]store.go:47 auth/domain/store.(*Store).Open Auth store opening. Source: host=localhost port=8082 user=user password=userpass dbname=authdbtest sslmode=disable 
[36mINFO[0m[2022-03-27T12:37:46Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:37:46Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:37:46Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:37:46Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-03-27T12:37:46Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.26.0.2:5432: connect: connection refused 
[31mERRO[0m[2022-03-27T12:37:46Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.26.0.2:5432: connect: connection refused 
[31mERRO[0m[2022-03-27T12:37:46Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00038a120 0xc0003a6000}) 
[31mERRO[0m[2022-03-27T12:37:46Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00038a120 0xc0003a6000}) 
[31mERRO[0m[2022-03-27T12:37:46Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00038a120 0xc0003a6000}) 
[31mERRO[0m[2022-03-27T12:37:46Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00038a120 0xc0003a6000}) 
[36mINFO[0m[2022-03-27T12:38:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:38:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:38:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:38:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:38:00Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-03-27T12:38:00Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-03-27T12:39:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:39:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-03-27T12:39:10Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:39:10Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:39:10Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-03-27T12:39:10Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[31mERRO[0m[2022-03-27T12:39:23Z]helper.go:138 auth/pkg/jwt.ExtractTokenMetadata you are unauthorized. err: %!w(*jwt.ValidationError=&{<nil> 1 token contains an invalid number of segments}) 
[31mERRO[0m[2022-03-27T12:39:23Z]helper.go:138 auth/pkg/jwt.ExtractTokenMetadata you are unauthorized. err: %!w(*jwt.ValidationError=&{<nil> 1 token contains an invalid number of segments}) 
[36mINFO[0m[2022-03-27T12:39:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:39:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:39:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-03-27T12:39:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:10Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:10Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:23:10Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:10Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:10Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:10Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:10Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[36mINFO[0m[2022-04-12T08:23:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:14Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:14Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:23:14Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:14Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:14Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:23:14Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:23:14Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:23:14Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a570 0xc00004e180}) 
[36mINFO[0m[2022-04-12T08:23:23Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:23Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:23Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:23:23Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:23Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:23Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:23:23Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:23:23Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:23:23Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[36mINFO[0m[2022-04-12T08:23:30Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:30Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:30Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:30Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:23:31Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:31Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:31Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ae000}) 
[31mERRO[0m[2022-04-12T08:23:31Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ae000}) 
[31mERRO[0m[2022-04-12T08:23:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ae000}) 
[31mERRO[0m[2022-04-12T08:23:31Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ae000}) 
[36mINFO[0m[2022-04-12T08:23:41Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:41Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:41Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:41Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:23:42Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:42Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.19.0.4:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:23:42Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:42Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:23:42Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[36mINFO[0m[2022-04-12T08:23:52Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:52Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:23:52Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:52Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:23:52Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:23:52Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:26:40Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:26:40Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:26:40Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:26:40Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:26:40Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:26:40Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:38:45Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:45Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:38:45Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:38:45Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:38:45Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:38:45Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:44:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:44:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:44:13Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.2:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:44:13Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.2:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:44:13Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:44:13Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:44:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc00004e180}) 
[31mERRO[0m[2022-04-12T08:44:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc00004e180}) 
[36mINFO[0m[2022-04-12T08:44:28Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:28Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:44:28Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:44:28Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:44:29Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:44:29Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:49:04Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:49:04Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:49:04Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T08:58:43Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:58:43Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:58:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:58:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:58:46Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: no route to host 
[31mERRO[0m[2022-04-12T08:58:46Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: no route to host 
[31mERRO[0m[2022-04-12T08:58:46Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc000225740}) 
[31mERRO[0m[2022-04-12T08:58:46Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc000225740}) 
[31mERRO[0m[2022-04-12T08:58:46Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc000225740}) 
[31mERRO[0m[2022-04-12T08:58:46Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00006a540 0xc000225740}) 
[36mINFO[0m[2022-04-12T08:59:01Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:01Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:01Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:59:01Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:59:01Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:01Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:01Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:59:01Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:59:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T08:59:01Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[36mINFO[0m[2022-04-12T08:59:19Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:19Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:19Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:59:19Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:59:19Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:19Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:19Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:19Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:19Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:19Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000225880}) 
[36mINFO[0m[2022-04-12T08:59:32Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:32Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:32Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:59:32Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:59:32Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:32Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:32Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:59:32Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:59:32Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T08:59:32Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:58Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T08:59:58Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T08:59:58Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T08:59:58Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:58Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.11:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T08:59:58Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:58Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T08:59:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:00:14Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:00:14Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:00:14Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:11:24Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:24Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:24Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:11:24Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:11:25Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:25Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:25Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:11:25Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:11:25Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:11:25Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[36mINFO[0m[2022-04-12T09:11:41Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:41Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:41Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:11:41Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:11:41Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:41Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:41Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00024fb90 0xc000255700}) 
[31mERRO[0m[2022-04-12T09:11:41Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc00024fb90 0xc000255700}) 
[31mERRO[0m[2022-04-12T09:11:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00024fb90 0xc000255700}) 
[31mERRO[0m[2022-04-12T09:11:41Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc00024fb90 0xc000255700}) 
[36mINFO[0m[2022-04-12T09:11:53Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:53Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:11:53Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:11:53Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:11:54Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:54Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:11:54Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ac000}) 
[31mERRO[0m[2022-04-12T09:11:54Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ac000}) 
[31mERRO[0m[2022-04-12T09:11:54Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ac000}) 
[31mERRO[0m[2022-04-12T09:11:54Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000296120 0xc0002ac000}) 
[36mINFO[0m[2022-04-12T09:12:15Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:15Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:15Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:12:15Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:12:15Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:12:15Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:12:15Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0000680f0 0xc00004e020}) 
[31mERRO[0m[2022-04-12T09:12:15Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0000680f0 0xc00004e020}) 
[31mERRO[0m[2022-04-12T09:12:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0000680f0 0xc00004e020}) 
[31mERRO[0m[2022-04-12T09:12:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0000680f0 0xc00004e020}) 
[36mINFO[0m[2022-04-12T09:12:28Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:28Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:12:28Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:12:28Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:12:28Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:12:28Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:33:45Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:33:45Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:33:45Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:33:45Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:33:45Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:33:45Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:33:45Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:33:45Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:33:45Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:33:45Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[36mINFO[0m[2022-04-12T09:34:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:34:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:34:00Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:00Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:00Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T09:34:00Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T09:34:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T09:34:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[36mINFO[0m[2022-04-12T09:34:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:10Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:11Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:34:11Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:34:11Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:11Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:11Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:34:11Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:34:11Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T09:34:11Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[36mINFO[0m[2022-04-12T09:34:27Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:27Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:27Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:34:27Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T09:34:27Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:27Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T09:34:27Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000294000 0xc00029c000}) 
[31mERRO[0m[2022-04-12T09:34:27Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000294000 0xc00029c000}) 
[31mERRO[0m[2022-04-12T09:34:27Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000294000 0xc00029c000}) 
[31mERRO[0m[2022-04-12T09:34:27Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000294000 0xc00029c000}) 
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:34:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:34:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:34:35Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:39:18Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:39:18Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T09:39:18Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:39:18Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T09:39:18Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T09:39:18Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T11:43:46Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:43:46Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:43:46Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:43:46Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T11:43:48Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:43:48Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:43:48Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:43:48Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:43:48Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:43:48Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[36mINFO[0m[2022-04-12T11:44:03Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:03Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:03Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:03Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T11:44:03Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:03Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:03Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:03Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:03Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:03Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[36mINFO[0m[2022-04-12T11:44:17Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:17Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:17Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:17Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T11:44:17Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:17Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:17Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:17Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:17Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[31mERRO[0m[2022-04-12T11:44:17Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000223880}) 
[36mINFO[0m[2022-04-12T11:44:29Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:29Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:29Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:29Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T11:44:29Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:29Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:29Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-12T11:44:29Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-12T11:44:29Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[31mERRO[0m[2022-04-12T11:44:29Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000094120 0xc0000a8000}) 
[36mINFO[0m[2022-04-12T11:44:43Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:43Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T11:44:43Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:43Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.16:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T11:44:43Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068030 0xc00004e020}) 
[31mERRO[0m[2022-04-12T11:44:43Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068030 0xc00004e020}) 
[31mERRO[0m[2022-04-12T11:44:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068030 0xc00004e020}) 
[31mERRO[0m[2022-04-12T11:44:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068030 0xc00004e020}) 
[36mINFO[0m[2022-04-12T11:44:52Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:52Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T11:44:52Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:52Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T11:44:52Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T11:44:52Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:18:05Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:05Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:05Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:18:05Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:18:07Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:07Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:07Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:18:07Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:18:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:18:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000072120 0xc000225880}) 
[36mINFO[0m[2022-04-12T12:18:20Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:20Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:20Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:18:20Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:18:21Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:21Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:21Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000251cb0 0xc000257720}) 
[31mERRO[0m[2022-04-12T12:18:21Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000251cb0 0xc000257720}) 
[31mERRO[0m[2022-04-12T12:18:21Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000251cb0 0xc000257720}) 
[31mERRO[0m[2022-04-12T12:18:21Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000251cb0 0xc000257720}) 
[36mINFO[0m[2022-04-12T12:18:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:18:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:18:35Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:35Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.20.0.5:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:18:35Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:18:35Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:18:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:18:36Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[36mINFO[0m[2022-04-12T12:18:49Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:49Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:18:49Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:18:49Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:18:49Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:18:49Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:35:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:14Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:15Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:35:15Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:35:15Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:15Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:15Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:15Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:15Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[36mINFO[0m[2022-04-12T12:35:29Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:29Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:30Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:35:30Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:35:30Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:30Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:30Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:30Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:30Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:35:30Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[36mINFO[0m[2022-04-12T12:35:58Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:58Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:35:58Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:35:58Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:35:58Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:58Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.21.0.13:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:35:58Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068120 0xc000056020}) 
[31mERRO[0m[2022-04-12T12:35:58Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068120 0xc000056020}) 
[31mERRO[0m[2022-04-12T12:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068120 0xc000056020}) 
[31mERRO[0m[2022-04-12T12:35:58Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068120 0xc000056020}) 
[36mINFO[0m[2022-04-12T12:36:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:36:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:36:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:36:13Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:36:13Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:45:44Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:45:44Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:45:44Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:45:44Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:45:44Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:45:44Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:45:44Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000274150 0xc0001e98a0}) 
[31mERRO[0m[2022-04-12T12:45:44Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000274150 0xc0001e98a0}) 
[31mERRO[0m[2022-04-12T12:45:44Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000274150 0xc0001e98a0}) 
[31mERRO[0m[2022-04-12T12:45:44Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000274150 0xc0001e98a0}) 
[36mINFO[0m[2022-04-12T12:45:50Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:45:50Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:45:50Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:45:50Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:45:50Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:45:50Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:45:50Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:45:50Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:45:50Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:45:50Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc150 0xc000223880}) 
[36mINFO[0m[2022-04-12T12:46:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:00Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:00Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:46:00Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:00Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:00Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000294030 0xc00029e000}) 
[31mERRO[0m[2022-04-12T12:46:00Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000294030 0xc00029e000}) 
[31mERRO[0m[2022-04-12T12:46:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000294030 0xc00029e000}) 
[31mERRO[0m[2022-04-12T12:46:00Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000294030 0xc00029e000}) 
[36mINFO[0m[2022-04-12T12:46:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:13Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:13Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:46:13Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:13Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:13Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000251bc0 0xc000257700}) 
[31mERRO[0m[2022-04-12T12:46:13Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000251bc0 0xc000257700}) 
[31mERRO[0m[2022-04-12T12:46:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000251bc0 0xc000257700}) 
[31mERRO[0m[2022-04-12T12:46:13Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000251bc0 0xc000257700}) 
[36mINFO[0m[2022-04-12T12:46:26Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:26Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:26Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:26Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:46:26Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:26Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:26Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:26Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:26Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:26Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc0f0 0xc000225880}) 
[36mINFO[0m[2022-04-12T12:46:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:46:35Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:35Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.22.0.15:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:46:35Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:35Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:35Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[31mERRO[0m[2022-04-12T12:46:35Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000225880}) 
[36mINFO[0m[2022-04-12T12:46:47Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:47Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:46:47Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:47Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:46:47Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:46:47Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:50:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:50:35Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:50:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:50:35Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:50:35Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:50:35Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:55:42Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:42Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:55:43Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:55:43Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:55:43Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:55:43Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:43Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[31mERRO[0m[2022-04-12T12:55:43Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc000068150 0xc00004e020}) 
[36mINFO[0m[2022-04-12T12:55:53Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:53Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:55:53Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:55:53Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:55:53Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:55:53Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:55:53Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T12:55:53Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T12:55:53Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[31mERRO[0m[2022-04-12T12:55:53Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0001f3ce0 0xc000225740}) 
[36mINFO[0m[2022-04-12T12:56:07Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:07Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:07Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:56:07Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:56:07Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:56:07Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:56:07Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:56:07Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:56:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[31mERRO[0m[2022-04-12T12:56:07Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002bc120 0xc000223880}) 
[36mINFO[0m[2022-04-12T12:56:25Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:25Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:25Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:56:25Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[31mERRO[0m[2022-04-12T12:56:25Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:56:25Z]store.go:66 auth/domain/store.(*Store).Open Can't ping DB. Err msg: dial tcp 172.23.0.8:5432: connect: connection refused 
[31mERRO[0m[2022-04-12T12:56:25Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002740f0 0xc0001eb8a0}) 
[31mERRO[0m[2022-04-12T12:56:25Z]server.go:37 auth/internal/server.(*Server).Start err during db opening, err: %!w(*net.OpError=&{dial tcp <nil> 0xc0002740f0 0xc0001eb8a0}) 
[31mERRO[0m[2022-04-12T12:56:25Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002740f0 0xc0001eb8a0}) 
[31mERRO[0m[2022-04-12T12:56:25Z]main.go:14 main.main failed to start server due to error: %!w(*net.OpError=&{dial tcp <nil> 0xc0002740f0 0xc0001eb8a0}) 
[36mINFO[0m[2022-04-12T12:56:40Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:40Z]server.go:34 auth/internal/server.(*Server).Start Router started successfully                  
[36mINFO[0m[2022-04-12T12:56:40Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:56:40Z]store.go:57 auth/domain/store.(*Store).Open Auth store opening. Source: host=authdb port=5432 user=user password=userpass dbname=authdb sslmode=disable 
[36mINFO[0m[2022-04-12T12:56:40Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
[36mINFO[0m[2022-04-12T12:56:40Z]server.go:56 auth/internal/server.(*Server).Start Auth server starts at 0.0.0.0:1111 ...       
